cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\DropQueriesDBScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\IndividualVelocityScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\JiraffeLeaderboardsScript &
node individual.js &
node team.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\IndividualMaturityScript &
node individual.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\LeaderboardCollectionScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\MaturityCollectionScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\PersonalDashboardScript &
node jiraffe.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\SearchBarCollectionScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\TeamInfoCollectionScript &
node app.js &
cd %SystemRoot% &
cd .. &
cd DB_Setup\MongoDB\JavaScripts_CalculateMetrics\TeamTypeScript &
node app.js &
exit